[profile.default]
src = "src"
out = "out"
libs = ["lib"]

optimizer_runs = 200

remappings = [
    "eigenlayer-middleware/=lib/eigenlayer-middleware/",
    "eigenlayer-core/=lib/eigenlayer-middleware/lib/eigenlayer-contracts/src/",
    "openzeppelin-contracts/=lib/eigenlayer-middleware/lib/openzeppelin-contracts/",
]

fs_permissions = [{ access = "read-write", path = "./"}]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
