name: tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  TestGo:
    name: Go tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      - name: Unit Test
        run: cd go && make tests
  TestRs:
    name: Rust tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      - name: Unit Test
        run: cd rs && cargo test